/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.mltframework;

public class Consumer extends Service {
  private long swigCPtr;

  protected Consumer(long cPtr, boolean cMemoryOwn) {
    super(mltJNI.Consumer_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Consumer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mltJNI.delete_Consumer(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Consumer() {
    this(mltJNI.new_Consumer__SWIG_0(), true);
  }

  public Consumer(Profile profile) {
    this(mltJNI.new_Consumer__SWIG_1(Profile.getCPtr(profile), profile), true);
  }

  public Consumer(Profile profile, String id, String service) {
    this(mltJNI.new_Consumer__SWIG_2(Profile.getCPtr(profile), profile, id, service), true);
  }

  public Consumer(Profile profile, String id) {
    this(mltJNI.new_Consumer__SWIG_3(Profile.getCPtr(profile), profile, id), true);
  }

  public Consumer(Service consumer) {
    this(mltJNI.new_Consumer__SWIG_4(Service.getCPtr(consumer), consumer), true);
  }

  public Consumer(Consumer consumer) {
    this(mltJNI.new_Consumer__SWIG_5(Consumer.getCPtr(consumer), consumer), true);
  }

  public Consumer(SWIGTYPE_p_mlt_consumer_s consumer) {
    this(mltJNI.new_Consumer__SWIG_6(SWIGTYPE_p_mlt_consumer_s.getCPtr(consumer)), true);
  }

  public SWIGTYPE_p_mlt_consumer_s get_consumer() {
    long cPtr = mltJNI.Consumer_get_consumer(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_mlt_consumer_s(cPtr, false);
  }

  public SWIGTYPE_p_mlt_service_s get_service() {
    long cPtr = mltJNI.Consumer_get_service(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_mlt_service_s(cPtr, false);
  }

  public int connect(Service service) {
    return mltJNI.Consumer_connect(swigCPtr, this, Service.getCPtr(service), service);
  }

  public int run() {
    return mltJNI.Consumer_run(swigCPtr, this);
  }

  public int start() {
    return mltJNI.Consumer_start(swigCPtr, this);
  }

  public void purge() {
    mltJNI.Consumer_purge(swigCPtr, this);
  }

  public int stop() {
    return mltJNI.Consumer_stop(swigCPtr, this);
  }

  public boolean is_stopped() {
    return mltJNI.Consumer_is_stopped(swigCPtr, this);
  }

  public int position() {
    return mltJNI.Consumer_position(swigCPtr, this);
  }

}
