/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.mltframework;

public class Event {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Event(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Event obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mltJNI.delete_Event(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Event(SWIGTYPE_p_mlt_event_struct arg0) {
    this(mltJNI.new_Event__SWIG_0(SWIGTYPE_p_mlt_event_struct.getCPtr(arg0)), true);
  }

  public Event(Event arg0) {
    this(mltJNI.new_Event__SWIG_1(Event.getCPtr(arg0), arg0), true);
  }

  public SWIGTYPE_p_mlt_event_struct get_event() {
    long cPtr = mltJNI.Event_get_event(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_mlt_event_struct(cPtr, false);
  }

  public boolean is_valid() {
    return mltJNI.Event_is_valid(swigCPtr, this);
  }

  public void block() {
    mltJNI.Event_block(swigCPtr, this);
  }

  public void unblock() {
    mltJNI.Event_unblock(swigCPtr, this);
  }

}
