/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.mltframework;

public class Field extends Service {
  private long swigCPtr;

  protected Field(long cPtr, boolean cMemoryOwn) {
    super(mltJNI.Field_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Field obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mltJNI.delete_Field(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Field(SWIGTYPE_p_mlt_field_s field) {
    this(mltJNI.new_Field__SWIG_0(SWIGTYPE_p_mlt_field_s.getCPtr(field)), true);
  }

  public Field(Field field) {
    this(mltJNI.new_Field__SWIG_1(Field.getCPtr(field), field), true);
  }

  public SWIGTYPE_p_mlt_field_s get_field() {
    long cPtr = mltJNI.Field_get_field(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_mlt_field_s(cPtr, false);
  }

  public SWIGTYPE_p_mlt_service_s get_service() {
    long cPtr = mltJNI.Field_get_service(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_mlt_service_s(cPtr, false);
  }

  public int plant_filter(Filter filter, int track) {
    return mltJNI.Field_plant_filter__SWIG_0(swigCPtr, this, Filter.getCPtr(filter), filter, track);
  }

  public int plant_filter(Filter filter) {
    return mltJNI.Field_plant_filter__SWIG_1(swigCPtr, this, Filter.getCPtr(filter), filter);
  }

  public int plant_transition(Transition transition, int a_track, int b_track) {
    return mltJNI.Field_plant_transition__SWIG_0(swigCPtr, this, Transition.getCPtr(transition), transition, a_track, b_track);
  }

  public int plant_transition(Transition transition, int a_track) {
    return mltJNI.Field_plant_transition__SWIG_1(swigCPtr, this, Transition.getCPtr(transition), transition, a_track);
  }

  public int plant_transition(Transition transition) {
    return mltJNI.Field_plant_transition__SWIG_2(swigCPtr, this, Transition.getCPtr(transition), transition);
  }

  public void disconnect_service(Service service) {
    mltJNI.Field_disconnect_service(swigCPtr, this, Service.getCPtr(service), service);
  }

}
