/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.mltframework;

public class Frame extends Properties {
  private long swigCPtr;

  protected Frame(long cPtr, boolean cMemoryOwn) {
    super(mltJNI.Frame_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Frame obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mltJNI.delete_Frame(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Frame() {
    this(mltJNI.new_Frame__SWIG_0(), true);
  }

  public Frame(SWIGTYPE_p_mlt_frame_s frame) {
    this(mltJNI.new_Frame__SWIG_1(SWIGTYPE_p_mlt_frame_s.getCPtr(frame)), true);
  }

  public Frame(Frame frame) {
    this(mltJNI.new_Frame__SWIG_2(Frame.getCPtr(frame), frame), true);
  }

  public SWIGTYPE_p_mlt_frame_s get_frame() {
    long cPtr = mltJNI.Frame_get_frame(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_mlt_frame_s(cPtr, false);
  }

  public SWIGTYPE_p_mlt_properties_s get_properties() {
    long cPtr = mltJNI.Frame_get_properties(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_mlt_properties_s(cPtr, false);
  }

  public SWIGTYPE_p_uint8_t get_image(SWIGTYPE_p_mlt_image_format format, SWIGTYPE_p_int w, SWIGTYPE_p_int h, int writable) {
    long cPtr = mltJNI.Frame_get_image__SWIG_0(swigCPtr, this, SWIGTYPE_p_mlt_image_format.getCPtr(format), SWIGTYPE_p_int.getCPtr(w), SWIGTYPE_p_int.getCPtr(h), writable);
    return (cPtr == 0) ? null : new SWIGTYPE_p_uint8_t(cPtr, false);
  }

  public SWIGTYPE_p_uint8_t get_image(SWIGTYPE_p_mlt_image_format format, SWIGTYPE_p_int w, SWIGTYPE_p_int h) {
    long cPtr = mltJNI.Frame_get_image__SWIG_1(swigCPtr, this, SWIGTYPE_p_mlt_image_format.getCPtr(format), SWIGTYPE_p_int.getCPtr(w), SWIGTYPE_p_int.getCPtr(h));
    return (cPtr == 0) ? null : new SWIGTYPE_p_uint8_t(cPtr, false);
  }

  public SWIGTYPE_p_unsigned_char fetch_image(mlt_image_format format, int w, int h, int writable) {
    long cPtr = mltJNI.Frame_fetch_image__SWIG_0(swigCPtr, this, format.swigValue(), w, h, writable);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public SWIGTYPE_p_unsigned_char fetch_image(mlt_image_format format, int w, int h) {
    long cPtr = mltJNI.Frame_fetch_image__SWIG_1(swigCPtr, this, format.swigValue(), w, h);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public SWIGTYPE_p_void get_audio(SWIGTYPE_p_mlt_audio_format format, SWIGTYPE_p_int frequency, SWIGTYPE_p_int channels, SWIGTYPE_p_int samples) {
    long cPtr = mltJNI.Frame_get_audio(swigCPtr, this, SWIGTYPE_p_mlt_audio_format.getCPtr(format), SWIGTYPE_p_int.getCPtr(frequency), SWIGTYPE_p_int.getCPtr(channels), SWIGTYPE_p_int.getCPtr(samples));
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public SWIGTYPE_p_unsigned_char get_waveform(int w, int h) {
    long cPtr = mltJNI.Frame_get_waveform(swigCPtr, this, w, h);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public Producer get_original_producer() {
    long cPtr = mltJNI.Frame_get_original_producer(swigCPtr, this);
    return (cPtr == 0) ? null : new Producer(cPtr, true);
  }

  public int get_position() {
    return mltJNI.Frame_get_position(swigCPtr, this);
  }

  public SWIGTYPE_p_mlt_properties_s get_unique_properties(Service service) {
    long cPtr = mltJNI.Frame_get_unique_properties(swigCPtr, this, Service.getCPtr(service), service);
    return (cPtr == 0) ? null : new SWIGTYPE_p_mlt_properties_s(cPtr, false);
  }

  public int set_image(SWIGTYPE_p_uint8_t image, int size, SWIGTYPE_p_f_p_void__void destroy) {
    return mltJNI.Frame_set_image(swigCPtr, this, SWIGTYPE_p_uint8_t.getCPtr(image), size, SWIGTYPE_p_f_p_void__void.getCPtr(destroy));
  }

  public int set_alpha(SWIGTYPE_p_uint8_t alpha, int size, SWIGTYPE_p_f_p_void__void destroy) {
    return mltJNI.Frame_set_alpha(swigCPtr, this, SWIGTYPE_p_uint8_t.getCPtr(alpha), size, SWIGTYPE_p_f_p_void__void.getCPtr(destroy));
  }

}
