/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.mltframework;

public class Geometry {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Geometry(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Geometry obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mltJNI.delete_Geometry(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Geometry(String data, int length, int nw, int nh) {
    this(mltJNI.new_Geometry__SWIG_0(data, length, nw, nh), true);
  }

  public Geometry(String data, int length, int nw) {
    this(mltJNI.new_Geometry__SWIG_1(data, length, nw), true);
  }

  public Geometry(String data, int length) {
    this(mltJNI.new_Geometry__SWIG_2(data, length), true);
  }

  public Geometry(String data) {
    this(mltJNI.new_Geometry__SWIG_3(data), true);
  }

  public Geometry() {
    this(mltJNI.new_Geometry__SWIG_4(), true);
  }

  public int parse(String data, int length, int nw, int nh) {
    return mltJNI.Geometry_parse__SWIG_0(swigCPtr, this, data, length, nw, nh);
  }

  public int parse(String data, int length, int nw) {
    return mltJNI.Geometry_parse__SWIG_1(swigCPtr, this, data, length, nw);
  }

  public int parse(String data, int length) {
    return mltJNI.Geometry_parse__SWIG_2(swigCPtr, this, data, length);
  }

  public int fetch(GeometryItem item, float position) {
    return mltJNI.Geometry_fetch__SWIG_0(swigCPtr, this, GeometryItem.getCPtr(item), item, position);
  }

  public int insert(GeometryItem item) {
    return mltJNI.Geometry_insert__SWIG_0(swigCPtr, this, GeometryItem.getCPtr(item), item);
  }

  public int remove(int position) {
    return mltJNI.Geometry_remove(swigCPtr, this, position);
  }

  public void interpolate() {
    mltJNI.Geometry_interpolate(swigCPtr, this);
  }

  public int next_key(GeometryItem item, int position) {
    return mltJNI.Geometry_next_key__SWIG_0(swigCPtr, this, GeometryItem.getCPtr(item), item, position);
  }

  public int prev_key(GeometryItem item, int position) {
    return mltJNI.Geometry_prev_key__SWIG_0(swigCPtr, this, GeometryItem.getCPtr(item), item, position);
  }

  public String serialise(int in, int out) {
    return mltJNI.Geometry_serialise__SWIG_0(swigCPtr, this, in, out);
  }

  public String serialise() {
    return mltJNI.Geometry_serialise__SWIG_1(swigCPtr, this);
  }

}
