/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.mltframework;

public class mlt implements mltConstants {
  public static SWIGTYPE_p_mlt_repository_s mlt_factory_init(String directory) {
    long cPtr = mltJNI.mlt_factory_init(directory);
    return (cPtr == 0) ? null : new SWIGTYPE_p_mlt_repository_s(cPtr, false);
  }

  public static String mlt_factory_directory() {
    return mltJNI.mlt_factory_directory();
  }

  public static String mlt_environment(String name) {
    return mltJNI.mlt_environment(name);
  }

  public static int mlt_environment_set(String name, String value) {
    return mltJNI.mlt_environment_set(name, value);
  }

  public static SWIGTYPE_p_mlt_properties_s mlt_factory_event_object() {
    long cPtr = mltJNI.mlt_factory_event_object();
    return (cPtr == 0) ? null : new SWIGTYPE_p_mlt_properties_s(cPtr, false);
  }

  public static SWIGTYPE_p_mlt_producer_s mlt_factory_producer(SWIGTYPE_p_mlt_profile_s profile, String service, SWIGTYPE_p_void resource) {
    long cPtr = mltJNI.mlt_factory_producer(SWIGTYPE_p_mlt_profile_s.getCPtr(profile), service, SWIGTYPE_p_void.getCPtr(resource));
    return (cPtr == 0) ? null : new SWIGTYPE_p_mlt_producer_s(cPtr, false);
  }

  public static SWIGTYPE_p_mlt_filter_s mlt_factory_filter(SWIGTYPE_p_mlt_profile_s profile, String name, SWIGTYPE_p_void input) {
    long cPtr = mltJNI.mlt_factory_filter(SWIGTYPE_p_mlt_profile_s.getCPtr(profile), name, SWIGTYPE_p_void.getCPtr(input));
    return (cPtr == 0) ? null : new SWIGTYPE_p_mlt_filter_s(cPtr, false);
  }

  public static SWIGTYPE_p_mlt_transition_s mlt_factory_transition(SWIGTYPE_p_mlt_profile_s profile, String name, SWIGTYPE_p_void input) {
    long cPtr = mltJNI.mlt_factory_transition(SWIGTYPE_p_mlt_profile_s.getCPtr(profile), name, SWIGTYPE_p_void.getCPtr(input));
    return (cPtr == 0) ? null : new SWIGTYPE_p_mlt_transition_s(cPtr, false);
  }

  public static SWIGTYPE_p_mlt_consumer_s mlt_factory_consumer(SWIGTYPE_p_mlt_profile_s profile, String name, SWIGTYPE_p_void input) {
    long cPtr = mltJNI.mlt_factory_consumer(SWIGTYPE_p_mlt_profile_s.getCPtr(profile), name, SWIGTYPE_p_void.getCPtr(input));
    return (cPtr == 0) ? null : new SWIGTYPE_p_mlt_consumer_s(cPtr, false);
  }

  public static void mlt_factory_register_for_clean_up(SWIGTYPE_p_void ptr, SWIGTYPE_p_f_p_void__void destructor) {
    mltJNI.mlt_factory_register_for_clean_up(SWIGTYPE_p_void.getCPtr(ptr), SWIGTYPE_p_f_p_void__void.getCPtr(destructor));
  }

  public static void mlt_factory_close() {
    mltJNI.mlt_factory_close();
  }

  public static SWIGTYPE_p_mlt_properties_s mlt_global_properties() {
    long cPtr = mltJNI.mlt_global_properties();
    return (cPtr == 0) ? null : new SWIGTYPE_p_mlt_properties_s(cPtr, false);
  }

  public static int mlt_version_get_int() {
    return mltJNI.mlt_version_get_int();
  }

  public static int mlt_version_get_major() {
    return mltJNI.mlt_version_get_major();
  }

  public static int mlt_version_get_minor() {
    return mltJNI.mlt_version_get_minor();
  }

  public static int mlt_version_get_revision() {
    return mltJNI.mlt_version_get_revision();
  }

  public static String mlt_version_get_string() {
    return mltJNI.mlt_version_get_string();
  }

  public static int mlt_log_get_level() {
    return mltJNI.mlt_log_get_level();
  }

  public static void mlt_log_set_level(int arg0) {
    mltJNI.mlt_log_set_level(arg0);
  }

}
