/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.mltframework;

public class mlt_rect {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected mlt_rect(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(mlt_rect obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mltJNI.delete_mlt_rect(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setX(double value) {
    mltJNI.mlt_rect_x_set(swigCPtr, this, value);
  }

  public double getX() {
    return mltJNI.mlt_rect_x_get(swigCPtr, this);
  }

  public void setY(double value) {
    mltJNI.mlt_rect_y_set(swigCPtr, this, value);
  }

  public double getY() {
    return mltJNI.mlt_rect_y_get(swigCPtr, this);
  }

  public void setW(double value) {
    mltJNI.mlt_rect_w_set(swigCPtr, this, value);
  }

  public double getW() {
    return mltJNI.mlt_rect_w_get(swigCPtr, this);
  }

  public void setH(double value) {
    mltJNI.mlt_rect_h_set(swigCPtr, this, value);
  }

  public double getH() {
    return mltJNI.mlt_rect_h_get(swigCPtr, this);
  }

  public void setO(double value) {
    mltJNI.mlt_rect_o_set(swigCPtr, this, value);
  }

  public double getO() {
    return mltJNI.mlt_rect_o_get(swigCPtr, this);
  }

  public mlt_rect() {
    this(mltJNI.new_mlt_rect(), true);
  }

}
