/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.mltframework;

public final class mlt_whence {
  public final static mlt_whence mlt_whence_relative_start = new mlt_whence("mlt_whence_relative_start", mltJNI.mlt_whence_relative_start_get());
  public final static mlt_whence mlt_whence_relative_current = new mlt_whence("mlt_whence_relative_current");
  public final static mlt_whence mlt_whence_relative_end = new mlt_whence("mlt_whence_relative_end");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static mlt_whence swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + mlt_whence.class + " with value " + swigValue);
  }

  private mlt_whence(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private mlt_whence(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private mlt_whence(String swigName, mlt_whence swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static mlt_whence[] swigValues = { mlt_whence_relative_start, mlt_whence_relative_current, mlt_whence_relative_end };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

