/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.mltframework;

public class Parser extends Properties {
  private long swigCPtr;

  protected Parser(long cPtr, boolean cMemoryOwn) {
    super(mltJNI.Parser_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Parser obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mltJNI.delete_Parser(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Parser() {
    this(mltJNI.new_Parser(), true);
  }

  public int start(Service service) {
    return mltJNI.Parser_start(swigCPtr, this, Service.getCPtr(service), service);
  }

  public SWIGTYPE_p_mlt_properties_s get_properties() {
    long cPtr = mltJNI.Parser_get_properties(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_mlt_properties_s(cPtr, false);
  }

  public int on_invalid(Service object) {
    return mltJNI.Parser_on_invalid(swigCPtr, this, Service.getCPtr(object), object);
  }

  public int on_unknown(Service object) {
    return mltJNI.Parser_on_unknown(swigCPtr, this, Service.getCPtr(object), object);
  }

  public int on_start_producer(Producer object) {
    return mltJNI.Parser_on_start_producer(swigCPtr, this, Producer.getCPtr(object), object);
  }

  public int on_end_producer(Producer object) {
    return mltJNI.Parser_on_end_producer(swigCPtr, this, Producer.getCPtr(object), object);
  }

  public int on_start_playlist(Playlist object) {
    return mltJNI.Parser_on_start_playlist(swigCPtr, this, Playlist.getCPtr(object), object);
  }

  public int on_end_playlist(Playlist object) {
    return mltJNI.Parser_on_end_playlist(swigCPtr, this, Playlist.getCPtr(object), object);
  }

  public int on_start_tractor(Tractor object) {
    return mltJNI.Parser_on_start_tractor(swigCPtr, this, Tractor.getCPtr(object), object);
  }

  public int on_end_tractor(Tractor object) {
    return mltJNI.Parser_on_end_tractor(swigCPtr, this, Tractor.getCPtr(object), object);
  }

  public int on_start_multitrack(Multitrack object) {
    return mltJNI.Parser_on_start_multitrack(swigCPtr, this, Multitrack.getCPtr(object), object);
  }

  public int on_end_multitrack(Multitrack object) {
    return mltJNI.Parser_on_end_multitrack(swigCPtr, this, Multitrack.getCPtr(object), object);
  }

  public int on_start_track() {
    return mltJNI.Parser_on_start_track(swigCPtr, this);
  }

  public int on_end_track() {
    return mltJNI.Parser_on_end_track(swigCPtr, this);
  }

  public int on_start_filter(Filter object) {
    return mltJNI.Parser_on_start_filter(swigCPtr, this, Filter.getCPtr(object), object);
  }

  public int on_end_filter(Filter object) {
    return mltJNI.Parser_on_end_filter(swigCPtr, this, Filter.getCPtr(object), object);
  }

  public int on_start_transition(Transition object) {
    return mltJNI.Parser_on_start_transition(swigCPtr, this, Transition.getCPtr(object), object);
  }

  public int on_end_transition(Transition object) {
    return mltJNI.Parser_on_end_transition(swigCPtr, this, Transition.getCPtr(object), object);
  }

}
