/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.mltframework;

public class Producer extends Service {
  private long swigCPtr;

  protected Producer(long cPtr, boolean cMemoryOwn) {
    super(mltJNI.Producer_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Producer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mltJNI.delete_Producer(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Producer() {
    this(mltJNI.new_Producer__SWIG_0(), true);
  }

  public Producer(Profile profile, String id, String service) {
    this(mltJNI.new_Producer__SWIG_1(Profile.getCPtr(profile), profile, id, service), true);
  }

  public Producer(Profile profile, String id) {
    this(mltJNI.new_Producer__SWIG_2(Profile.getCPtr(profile), profile, id), true);
  }

  public Producer(Service producer) {
    this(mltJNI.new_Producer__SWIG_3(Service.getCPtr(producer), producer), true);
  }

  public Producer(SWIGTYPE_p_mlt_producer_s producer) {
    this(mltJNI.new_Producer__SWIG_4(SWIGTYPE_p_mlt_producer_s.getCPtr(producer)), true);
  }

  public Producer(Producer producer) {
    this(mltJNI.new_Producer__SWIG_5(Producer.getCPtr(producer), producer), true);
  }

  public SWIGTYPE_p_mlt_producer_s get_producer() {
    long cPtr = mltJNI.Producer_get_producer(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_mlt_producer_s(cPtr, false);
  }

  public Producer parent() {
    return new Producer(mltJNI.Producer_parent(swigCPtr, this), false);
  }

  public SWIGTYPE_p_mlt_producer_s get_parent() {
    long cPtr = mltJNI.Producer_get_parent(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_mlt_producer_s(cPtr, false);
  }

  public SWIGTYPE_p_mlt_service_s get_service() {
    long cPtr = mltJNI.Producer_get_service(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_mlt_service_s(cPtr, false);
  }

  public int seek(int position) {
    return mltJNI.Producer_seek__SWIG_0(swigCPtr, this, position);
  }

  public int seek(String time) {
    return mltJNI.Producer_seek__SWIG_1(swigCPtr, this, time);
  }

  public int position() {
    return mltJNI.Producer_position(swigCPtr, this);
  }

  public int frame() {
    return mltJNI.Producer_frame(swigCPtr, this);
  }

  public String frame_time(mlt_time_format arg0) {
    return mltJNI.Producer_frame_time__SWIG_0(swigCPtr, this, arg0.swigValue());
  }

  public String frame_time() {
    return mltJNI.Producer_frame_time__SWIG_1(swigCPtr, this);
  }

  public int set_speed(double speed) {
    return mltJNI.Producer_set_speed(swigCPtr, this, speed);
  }

  public int pause() {
    return mltJNI.Producer_pause(swigCPtr, this);
  }

  public double get_speed() {
    return mltJNI.Producer_get_speed(swigCPtr, this);
  }

  public double get_fps() {
    return mltJNI.Producer_get_fps(swigCPtr, this);
  }

  public int set_in_and_out(int in, int out) {
    return mltJNI.Producer_set_in_and_out(swigCPtr, this, in, out);
  }

  public int get_in() {
    return mltJNI.Producer_get_in(swigCPtr, this);
  }

  public int get_out() {
    return mltJNI.Producer_get_out(swigCPtr, this);
  }

  public int get_length() {
    return mltJNI.Producer_get_length(swigCPtr, this);
  }

  public String get_length_time(mlt_time_format arg0) {
    return mltJNI.Producer_get_length_time__SWIG_0(swigCPtr, this, arg0.swigValue());
  }

  public String get_length_time() {
    return mltJNI.Producer_get_length_time__SWIG_1(swigCPtr, this);
  }

  public int get_playtime() {
    return mltJNI.Producer_get_playtime(swigCPtr, this);
  }

  public Producer cut(int in, int out) {
    long cPtr = mltJNI.Producer_cut__SWIG_0(swigCPtr, this, in, out);
    return (cPtr == 0) ? null : new Producer(cPtr, true);
  }

  public Producer cut(int in) {
    long cPtr = mltJNI.Producer_cut__SWIG_1(swigCPtr, this, in);
    return (cPtr == 0) ? null : new Producer(cPtr, false);
  }

  public Producer cut() {
    long cPtr = mltJNI.Producer_cut__SWIG_2(swigCPtr, this);
    return (cPtr == 0) ? null : new Producer(cPtr, false);
  }

  public boolean is_cut() {
    return mltJNI.Producer_is_cut(swigCPtr, this);
  }

  public boolean is_blank() {
    return mltJNI.Producer_is_blank(swigCPtr, this);
  }

  public boolean same_clip(Producer that) {
    return mltJNI.Producer_same_clip(swigCPtr, this, Producer.getCPtr(that), that);
  }

  public boolean runs_into(Producer that) {
    return mltJNI.Producer_runs_into(swigCPtr, this, Producer.getCPtr(that), that);
  }

  public void optimise() {
    mltJNI.Producer_optimise(swigCPtr, this);
  }

  public int clear() {
    return mltJNI.Producer_clear(swigCPtr, this);
  }

}
