/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.mltframework;

public class Profile {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Profile(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Profile obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mltJNI.delete_Profile(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Profile() {
    this(mltJNI.new_Profile__SWIG_0(), true);
  }

  public Profile(String name) {
    this(mltJNI.new_Profile__SWIG_1(name), true);
  }

  public Profile(Properties properties) {
    this(mltJNI.new_Profile__SWIG_2(Properties.getCPtr(properties), properties), true);
  }

  public Profile(SWIGTYPE_p_mlt_profile_s profile) {
    this(mltJNI.new_Profile__SWIG_3(SWIGTYPE_p_mlt_profile_s.getCPtr(profile)), true);
  }

  public SWIGTYPE_p_mlt_profile_s get_profile() {
    long cPtr = mltJNI.Profile_get_profile(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_mlt_profile_s(cPtr, false);
  }

  public String description() {
    return mltJNI.Profile_description(swigCPtr, this);
  }

  public int frame_rate_num() {
    return mltJNI.Profile_frame_rate_num(swigCPtr, this);
  }

  public int frame_rate_den() {
    return mltJNI.Profile_frame_rate_den(swigCPtr, this);
  }

  public double fps() {
    return mltJNI.Profile_fps(swigCPtr, this);
  }

  public int width() {
    return mltJNI.Profile_width(swigCPtr, this);
  }

  public int height() {
    return mltJNI.Profile_height(swigCPtr, this);
  }

  public boolean progressive() {
    return mltJNI.Profile_progressive(swigCPtr, this);
  }

  public int sample_aspect_num() {
    return mltJNI.Profile_sample_aspect_num(swigCPtr, this);
  }

  public int sample_aspect_den() {
    return mltJNI.Profile_sample_aspect_den(swigCPtr, this);
  }

  public double sar() {
    return mltJNI.Profile_sar(swigCPtr, this);
  }

  public int display_aspect_num() {
    return mltJNI.Profile_display_aspect_num(swigCPtr, this);
  }

  public int display_aspect_den() {
    return mltJNI.Profile_display_aspect_den(swigCPtr, this);
  }

  public double dar() {
    return mltJNI.Profile_dar(swigCPtr, this);
  }

  public int is_explicit() {
    return mltJNI.Profile_is_explicit(swigCPtr, this);
  }

  public int colorspace() {
    return mltJNI.Profile_colorspace(swigCPtr, this);
  }

  public static Properties list() {
    long cPtr = mltJNI.Profile_list();
    return (cPtr == 0) ? null : new Properties(cPtr, true);
  }

  public void from_producer(Producer producer) {
    mltJNI.Profile_from_producer(swigCPtr, this, Producer.getCPtr(producer), producer);
  }

  public void set_width(int width) {
    mltJNI.Profile_set_width(swigCPtr, this, width);
  }

  public void set_height(int height) {
    mltJNI.Profile_set_height(swigCPtr, this, height);
  }

  public void set_sample_aspect(int numerator, int denominator) {
    mltJNI.Profile_set_sample_aspect(swigCPtr, this, numerator, denominator);
  }

  public void set_display_aspect(int numerator, int denominator) {
    mltJNI.Profile_set_display_aspect(swigCPtr, this, numerator, denominator);
  }

  public void set_progressive(int progressive) {
    mltJNI.Profile_set_progressive(swigCPtr, this, progressive);
  }

  public void set_colorspace(int colorspace) {
    mltJNI.Profile_set_colorspace(swigCPtr, this, colorspace);
  }

  public void set_frame_rate(int numerator, int denominator) {
    mltJNI.Profile_set_frame_rate(swigCPtr, this, numerator, denominator);
  }

  public void set_explicit(int arg0) {
    mltJNI.Profile_set_explicit(swigCPtr, this, arg0);
  }

}
