/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.mltframework;

public class Repository {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Repository(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Repository obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mltJNI.delete_Repository(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Repository(String directory) {
    this(mltJNI.new_Repository__SWIG_0(directory), true);
  }

  public Repository(SWIGTYPE_p_mlt_repository_s repository) {
    this(mltJNI.new_Repository__SWIG_1(SWIGTYPE_p_mlt_repository_s.getCPtr(repository)), true);
  }

  public void register_service(mlt_service_type service_type, String service, SWIGTYPE_p_mlt_register_callback symbol) {
    mltJNI.Repository_register_service(swigCPtr, this, service_type.swigValue(), service, SWIGTYPE_p_mlt_register_callback.getCPtr(symbol));
  }

  public SWIGTYPE_p_void create(Profile profile, mlt_service_type type, String service, SWIGTYPE_p_void arg) {
    long cPtr = mltJNI.Repository_create(swigCPtr, this, Profile.getCPtr(profile), profile, type.swigValue(), service, SWIGTYPE_p_void.getCPtr(arg));
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public Properties consumers() {
    long cPtr = mltJNI.Repository_consumers(swigCPtr, this);
    return (cPtr == 0) ? null : new Properties(cPtr, false);
  }

  public Properties filters() {
    long cPtr = mltJNI.Repository_filters(swigCPtr, this);
    return (cPtr == 0) ? null : new Properties(cPtr, false);
  }

  public Properties producers() {
    long cPtr = mltJNI.Repository_producers(swigCPtr, this);
    return (cPtr == 0) ? null : new Properties(cPtr, false);
  }

  public Properties transitions() {
    long cPtr = mltJNI.Repository_transitions(swigCPtr, this);
    return (cPtr == 0) ? null : new Properties(cPtr, false);
  }

  public void register_metadata(mlt_service_type type, String service, SWIGTYPE_p_mlt_metadata_callback arg2, SWIGTYPE_p_void callback_data) {
    mltJNI.Repository_register_metadata(swigCPtr, this, type.swigValue(), service, SWIGTYPE_p_mlt_metadata_callback.getCPtr(arg2), SWIGTYPE_p_void.getCPtr(callback_data));
  }

  public Properties metadata(mlt_service_type type, String service) {
    long cPtr = mltJNI.Repository_metadata(swigCPtr, this, type.swigValue(), service);
    return (cPtr == 0) ? null : new Properties(cPtr, false);
  }

  public Properties languages() {
    long cPtr = mltJNI.Repository_languages(swigCPtr, this);
    return (cPtr == 0) ? null : new Properties(cPtr, false);
  }

  public static Properties presets() {
    long cPtr = mltJNI.Repository_presets();
    return (cPtr == 0) ? null : new Properties(cPtr, true);
  }

}
