/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.mltframework;

public class Tractor extends Producer {
  private long swigCPtr;

  protected Tractor(long cPtr, boolean cMemoryOwn) {
    super(mltJNI.Tractor_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Tractor obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mltJNI.delete_Tractor(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Tractor() {
    this(mltJNI.new_Tractor__SWIG_0(), true);
  }

  public Tractor(Profile profile) {
    this(mltJNI.new_Tractor__SWIG_1(Profile.getCPtr(profile), profile), true);
  }

  public Tractor(Service tractor) {
    this(mltJNI.new_Tractor__SWIG_2(Service.getCPtr(tractor), tractor), true);
  }

  public Tractor(SWIGTYPE_p_mlt_tractor_s tractor) {
    this(mltJNI.new_Tractor__SWIG_3(SWIGTYPE_p_mlt_tractor_s.getCPtr(tractor)), true);
  }

  public Tractor(Tractor tractor) {
    this(mltJNI.new_Tractor__SWIG_4(Tractor.getCPtr(tractor), tractor), true);
  }

  public Tractor(Profile profile, String id, String arg) {
    this(mltJNI.new_Tractor__SWIG_5(Profile.getCPtr(profile), profile, id, arg), true);
  }

  public Tractor(Profile profile, String id) {
    this(mltJNI.new_Tractor__SWIG_6(Profile.getCPtr(profile), profile, id), true);
  }

  public SWIGTYPE_p_mlt_tractor_s get_tractor() {
    long cPtr = mltJNI.Tractor_get_tractor(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_mlt_tractor_s(cPtr, false);
  }

  public SWIGTYPE_p_mlt_producer_s get_producer() {
    long cPtr = mltJNI.Tractor_get_producer(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_mlt_producer_s(cPtr, false);
  }

  public Multitrack multitrack() {
    long cPtr = mltJNI.Tractor_multitrack(swigCPtr, this);
    return (cPtr == 0) ? null : new Multitrack(cPtr, true);
  }

  public Field field() {
    long cPtr = mltJNI.Tractor_field(swigCPtr, this);
    return (cPtr == 0) ? null : new Field(cPtr, true);
  }

  public void refresh() {
    mltJNI.Tractor_refresh(swigCPtr, this);
  }

  public int set_track(Producer producer, int index) {
    return mltJNI.Tractor_set_track(swigCPtr, this, Producer.getCPtr(producer), producer, index);
  }

  public Producer track(int index) {
    long cPtr = mltJNI.Tractor_track(swigCPtr, this, index);
    return (cPtr == 0) ? null : new Producer(cPtr, true);
  }

  public int count() {
    return mltJNI.Tractor_count(swigCPtr, this);
  }

  public void plant_transition(Transition transition, int a_track, int b_track) {
    mltJNI.Tractor_plant_transition__SWIG_0(swigCPtr, this, Transition.getCPtr(transition), transition, a_track, b_track);
  }

  public void plant_transition(Transition transition, int a_track) {
    mltJNI.Tractor_plant_transition__SWIG_1(swigCPtr, this, Transition.getCPtr(transition), transition, a_track);
  }

  public void plant_transition(Transition transition) {
    mltJNI.Tractor_plant_transition__SWIG_2(swigCPtr, this, Transition.getCPtr(transition), transition);
  }

  public void plant_filter(Filter filter, int track) {
    mltJNI.Tractor_plant_filter__SWIG_0(swigCPtr, this, Filter.getCPtr(filter), filter, track);
  }

  public void plant_filter(Filter filter) {
    mltJNI.Tractor_plant_filter__SWIG_1(swigCPtr, this, Filter.getCPtr(filter), filter);
  }

  public boolean locate_cut(Producer producer, SWIGTYPE_p_int track, SWIGTYPE_p_int cut) {
    return mltJNI.Tractor_locate_cut(swigCPtr, this, Producer.getCPtr(producer), producer, SWIGTYPE_p_int.getCPtr(track), SWIGTYPE_p_int.getCPtr(cut));
  }

  public int connect(Producer producer) {
    return mltJNI.Tractor_connect(swigCPtr, this, Producer.getCPtr(producer), producer);
  }

}
