/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.mltframework;

public class Transition extends Service {
  private long swigCPtr;

  protected Transition(long cPtr, boolean cMemoryOwn) {
    super(mltJNI.Transition_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Transition obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mltJNI.delete_Transition(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Transition(Profile profile, String id, String arg) {
    this(mltJNI.new_Transition__SWIG_0(Profile.getCPtr(profile), profile, id, arg), true);
  }

  public Transition(Profile profile, String id) {
    this(mltJNI.new_Transition__SWIG_1(Profile.getCPtr(profile), profile, id), true);
  }

  public Transition(Service transition) {
    this(mltJNI.new_Transition__SWIG_2(Service.getCPtr(transition), transition), true);
  }

  public Transition(Transition transition) {
    this(mltJNI.new_Transition__SWIG_3(Transition.getCPtr(transition), transition), true);
  }

  public Transition(SWIGTYPE_p_mlt_transition_s transition) {
    this(mltJNI.new_Transition__SWIG_4(SWIGTYPE_p_mlt_transition_s.getCPtr(transition)), true);
  }

  public SWIGTYPE_p_mlt_transition_s get_transition() {
    long cPtr = mltJNI.Transition_get_transition(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_mlt_transition_s(cPtr, false);
  }

  public SWIGTYPE_p_mlt_service_s get_service() {
    long cPtr = mltJNI.Transition_get_service(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_mlt_service_s(cPtr, false);
  }

  public void set_in_and_out(int in, int out) {
    mltJNI.Transition_set_in_and_out(swigCPtr, this, in, out);
  }

  public int connect(Producer producer, int a_track, int b_track) {
    return mltJNI.Transition_connect(swigCPtr, this, Producer.getCPtr(producer), producer, a_track, b_track);
  }

  public int get_a_track() {
    return mltJNI.Transition_get_a_track(swigCPtr, this);
  }

  public int get_b_track() {
    return mltJNI.Transition_get_b_track(swigCPtr, this);
  }

  public int get_in() {
    return mltJNI.Transition_get_in(swigCPtr, this);
  }

  public int get_out() {
    return mltJNI.Transition_get_out(swigCPtr, this);
  }

  public int get_length() {
    return mltJNI.Transition_get_length(swigCPtr, this);
  }

  public int get_position(Frame frame) {
    return mltJNI.Transition_get_position(swigCPtr, this, Frame.getCPtr(frame), frame);
  }

  public double get_progress(Frame frame) {
    return mltJNI.Transition_get_progress(swigCPtr, this, Frame.getCPtr(frame), frame);
  }

  public double get_progress_delta(Frame frame) {
    return mltJNI.Transition_get_progress_delta(swigCPtr, this, Frame.getCPtr(frame), frame);
  }

}
