/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.mltframework;

public class unsignedCharArray {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected unsignedCharArray(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(unsignedCharArray obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mltJNI.delete_unsignedCharArray(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public unsignedCharArray(int nelements) {
    this(mltJNI.new_unsignedCharArray(nelements), true);
  }

  public short getitem(int index) {
    return mltJNI.unsignedCharArray_getitem(swigCPtr, this, index);
  }

  public void setitem(int index, short value) {
    mltJNI.unsignedCharArray_setitem(swigCPtr, this, index, value);
  }

  public SWIGTYPE_p_unsigned_char cast() {
    long cPtr = mltJNI.unsignedCharArray_cast(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public static unsignedCharArray frompointer(SWIGTYPE_p_unsigned_char t) {
    long cPtr = mltJNI.unsignedCharArray_frompointer(SWIGTYPE_p_unsigned_char.getCPtr(t));
    return (cPtr == 0) ? null : new unsignedCharArray(cPtr, false);
  }

}
