/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.mltframework;

public class ClipInfo {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ClipInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ClipInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mltJNI.delete_ClipInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ClipInfo() {
    this(mltJNI.new_ClipInfo__SWIG_0(), true);
  }

  public ClipInfo(SWIGTYPE_p_mlt_playlist_clip_info info) {
    this(mltJNI.new_ClipInfo__SWIG_1(SWIGTYPE_p_mlt_playlist_clip_info.getCPtr(info)), true);
  }

  public void update(SWIGTYPE_p_mlt_playlist_clip_info info) {
    mltJNI.ClipInfo_update(swigCPtr, this, SWIGTYPE_p_mlt_playlist_clip_info.getCPtr(info));
  }

  public void setClip(int value) {
    mltJNI.ClipInfo_clip_set(swigCPtr, this, value);
  }

  public int getClip() {
    return mltJNI.ClipInfo_clip_get(swigCPtr, this);
  }

  public void setProducer(Producer value) {
    mltJNI.ClipInfo_producer_set(swigCPtr, this, Producer.getCPtr(value), value);
  }

  public Producer getProducer() {
    long cPtr = mltJNI.ClipInfo_producer_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Producer(cPtr, false);
  }

  public void setCut(Producer value) {
    mltJNI.ClipInfo_cut_set(swigCPtr, this, Producer.getCPtr(value), value);
  }

  public Producer getCut() {
    long cPtr = mltJNI.ClipInfo_cut_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Producer(cPtr, false);
  }

  public void setStart(int value) {
    mltJNI.ClipInfo_start_set(swigCPtr, this, value);
  }

  public int getStart() {
    return mltJNI.ClipInfo_start_get(swigCPtr, this);
  }

  public void setResource(String value) {
    mltJNI.ClipInfo_resource_set(swigCPtr, this, value);
  }

  public String getResource() {
    return mltJNI.ClipInfo_resource_get(swigCPtr, this);
  }

  public void setFrame_in(int value) {
    mltJNI.ClipInfo_frame_in_set(swigCPtr, this, value);
  }

  public int getFrame_in() {
    return mltJNI.ClipInfo_frame_in_get(swigCPtr, this);
  }

  public void setFrame_out(int value) {
    mltJNI.ClipInfo_frame_out_set(swigCPtr, this, value);
  }

  public int getFrame_out() {
    return mltJNI.ClipInfo_frame_out_get(swigCPtr, this);
  }

  public void setFrame_count(int value) {
    mltJNI.ClipInfo_frame_count_set(swigCPtr, this, value);
  }

  public int getFrame_count() {
    return mltJNI.ClipInfo_frame_count_get(swigCPtr, this);
  }

  public void setLength(int value) {
    mltJNI.ClipInfo_length_set(swigCPtr, this, value);
  }

  public int getLength() {
    return mltJNI.ClipInfo_length_get(swigCPtr, this);
  }

  public void setFps(float value) {
    mltJNI.ClipInfo_fps_set(swigCPtr, this, value);
  }

  public float getFps() {
    return mltJNI.ClipInfo_fps_get(swigCPtr, this);
  }

  public void setRepeat(int value) {
    mltJNI.ClipInfo_repeat_set(swigCPtr, this, value);
  }

  public int getRepeat() {
    return mltJNI.ClipInfo_repeat_get(swigCPtr, this);
  }

}
