/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.mltframework;

public class Factory {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Factory(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Factory obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mltJNI.delete_Factory(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static Repository init(String directory) {
    long cPtr = mltJNI.Factory_init__SWIG_0(directory);
    return (cPtr == 0) ? null : new Repository(cPtr, true);
  }

  public static Repository init() {
    long cPtr = mltJNI.Factory_init__SWIG_1();
    return (cPtr == 0) ? null : new Repository(cPtr, false);
  }

  public static Properties event_object() {
    long cPtr = mltJNI.Factory_event_object();
    return (cPtr == 0) ? null : new Properties(cPtr, false);
  }

  public static Producer producer(Profile profile, String id, String arg) {
    long cPtr = mltJNI.Factory_producer__SWIG_0(Profile.getCPtr(profile), profile, id, arg);
    return (cPtr == 0) ? null : new Producer(cPtr, true);
  }

  public static Producer producer(Profile profile, String id) {
    long cPtr = mltJNI.Factory_producer__SWIG_1(Profile.getCPtr(profile), profile, id);
    return (cPtr == 0) ? null : new Producer(cPtr, false);
  }

  public static Filter filter(Profile profile, String id, String arg) {
    long cPtr = mltJNI.Factory_filter__SWIG_0(Profile.getCPtr(profile), profile, id, arg);
    return (cPtr == 0) ? null : new Filter(cPtr, true);
  }

  public static Filter filter(Profile profile, String id) {
    long cPtr = mltJNI.Factory_filter__SWIG_1(Profile.getCPtr(profile), profile, id);
    return (cPtr == 0) ? null : new Filter(cPtr, false);
  }

  public static Transition transition(Profile profile, String id, String arg) {
    long cPtr = mltJNI.Factory_transition__SWIG_0(Profile.getCPtr(profile), profile, id, arg);
    return (cPtr == 0) ? null : new Transition(cPtr, true);
  }

  public static Transition transition(Profile profile, String id) {
    long cPtr = mltJNI.Factory_transition__SWIG_1(Profile.getCPtr(profile), profile, id);
    return (cPtr == 0) ? null : new Transition(cPtr, false);
  }

  public static Consumer consumer(Profile profile, String id, String arg) {
    long cPtr = mltJNI.Factory_consumer__SWIG_0(Profile.getCPtr(profile), profile, id, arg);
    return (cPtr == 0) ? null : new Consumer(cPtr, true);
  }

  public static Consumer consumer(Profile profile, String id) {
    long cPtr = mltJNI.Factory_consumer__SWIG_1(Profile.getCPtr(profile), profile, id);
    return (cPtr == 0) ? null : new Consumer(cPtr, false);
  }

  public static void close() {
    mltJNI.Factory_close();
  }

  public Factory() {
    this(mltJNI.new_Factory(), true);
  }

}
