/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.mltframework;

public class Filter extends Service {
  private long swigCPtr;

  protected Filter(long cPtr, boolean cMemoryOwn) {
    super(mltJNI.Filter_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Filter obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mltJNI.delete_Filter(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Filter(Profile profile, String id, String service) {
    this(mltJNI.new_Filter__SWIG_0(Profile.getCPtr(profile), profile, id, service), true);
  }

  public Filter(Profile profile, String id) {
    this(mltJNI.new_Filter__SWIG_1(Profile.getCPtr(profile), profile, id), true);
  }

  public Filter(Service filter) {
    this(mltJNI.new_Filter__SWIG_2(Service.getCPtr(filter), filter), true);
  }

  public Filter(Filter filter) {
    this(mltJNI.new_Filter__SWIG_3(Filter.getCPtr(filter), filter), true);
  }

  public Filter(SWIGTYPE_p_mlt_filter_s filter) {
    this(mltJNI.new_Filter__SWIG_4(SWIGTYPE_p_mlt_filter_s.getCPtr(filter)), true);
  }

  public SWIGTYPE_p_mlt_filter_s get_filter() {
    long cPtr = mltJNI.Filter_get_filter(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_mlt_filter_s(cPtr, false);
  }

  public SWIGTYPE_p_mlt_service_s get_service() {
    long cPtr = mltJNI.Filter_get_service(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_mlt_service_s(cPtr, false);
  }

  public int connect(Service service, int index) {
    return mltJNI.Filter_connect__SWIG_0(swigCPtr, this, Service.getCPtr(service), service, index);
  }

  public int connect(Service service) {
    return mltJNI.Filter_connect__SWIG_1(swigCPtr, this, Service.getCPtr(service), service);
  }

  public void set_in_and_out(int in, int out) {
    mltJNI.Filter_set_in_and_out(swigCPtr, this, in, out);
  }

  public int get_in() {
    return mltJNI.Filter_get_in(swigCPtr, this);
  }

  public int get_out() {
    return mltJNI.Filter_get_out(swigCPtr, this);
  }

  public int get_length() {
    return mltJNI.Filter_get_length(swigCPtr, this);
  }

  public int get_length2(Frame frame) {
    return mltJNI.Filter_get_length2(swigCPtr, this, Frame.getCPtr(frame), frame);
  }

  public int get_track() {
    return mltJNI.Filter_get_track(swigCPtr, this);
  }

  public int get_position(Frame frame) {
    return mltJNI.Filter_get_position(swigCPtr, this, Frame.getCPtr(frame), frame);
  }

  public double get_progress(Frame frame) {
    return mltJNI.Filter_get_progress(swigCPtr, this, Frame.getCPtr(frame), frame);
  }

  public void process(Frame frame) {
    mltJNI.Filter_process(swigCPtr, this, Frame.getCPtr(frame), frame);
  }

}
