/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.mltframework;

public final class mlt_time_format {
  public final static mlt_time_format mlt_time_frames = new mlt_time_format("mlt_time_frames", mltJNI.mlt_time_frames_get());
  public final static mlt_time_format mlt_time_clock = new mlt_time_format("mlt_time_clock");
  public final static mlt_time_format mlt_time_smpte_df = new mlt_time_format("mlt_time_smpte_df");
  public final static mlt_time_format mlt_time_smpte = new mlt_time_format("mlt_time_smpte", mltJNI.mlt_time_smpte_get());
  public final static mlt_time_format mlt_time_smpte_ndf = new mlt_time_format("mlt_time_smpte_ndf");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static mlt_time_format swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + mlt_time_format.class + " with value " + swigValue);
  }

  private mlt_time_format(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private mlt_time_format(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private mlt_time_format(String swigName, mlt_time_format swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static mlt_time_format[] swigValues = { mlt_time_frames, mlt_time_clock, mlt_time_smpte_df, mlt_time_smpte, mlt_time_smpte_ndf };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

