/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.mltframework;

public final class mlt_audio_format {
  public final static mlt_audio_format mlt_audio_none = new mlt_audio_format("mlt_audio_none", mltJNI.mlt_audio_none_get());
  public final static mlt_audio_format mlt_audio_pcm = new mlt_audio_format("mlt_audio_pcm", mltJNI.mlt_audio_pcm_get());
  public final static mlt_audio_format mlt_audio_s16 = new mlt_audio_format("mlt_audio_s16", mltJNI.mlt_audio_s16_get());
  public final static mlt_audio_format mlt_audio_s32 = new mlt_audio_format("mlt_audio_s32");
  public final static mlt_audio_format mlt_audio_float = new mlt_audio_format("mlt_audio_float");
  public final static mlt_audio_format mlt_audio_s32le = new mlt_audio_format("mlt_audio_s32le");
  public final static mlt_audio_format mlt_audio_f32le = new mlt_audio_format("mlt_audio_f32le");
  public final static mlt_audio_format mlt_audio_u8 = new mlt_audio_format("mlt_audio_u8");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static mlt_audio_format swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + mlt_audio_format.class + " with value " + swigValue);
  }

  private mlt_audio_format(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private mlt_audio_format(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private mlt_audio_format(String swigName, mlt_audio_format swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static mlt_audio_format[] swigValues = { mlt_audio_none, mlt_audio_pcm, mlt_audio_s16, mlt_audio_s32, mlt_audio_float, mlt_audio_s32le, mlt_audio_f32le, mlt_audio_u8 };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

