/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.mltframework;

public final class mlt_service_type {
  public final static mlt_service_type invalid_type = new mlt_service_type("invalid_type", mltJNI.invalid_type_get());
  public final static mlt_service_type unknown_type = new mlt_service_type("unknown_type");
  public final static mlt_service_type producer_type = new mlt_service_type("producer_type");
  public final static mlt_service_type tractor_type = new mlt_service_type("tractor_type");
  public final static mlt_service_type playlist_type = new mlt_service_type("playlist_type");
  public final static mlt_service_type multitrack_type = new mlt_service_type("multitrack_type");
  public final static mlt_service_type filter_type = new mlt_service_type("filter_type");
  public final static mlt_service_type transition_type = new mlt_service_type("transition_type");
  public final static mlt_service_type consumer_type = new mlt_service_type("consumer_type");
  public final static mlt_service_type field_type = new mlt_service_type("field_type");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static mlt_service_type swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + mlt_service_type.class + " with value " + swigValue);
  }

  private mlt_service_type(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private mlt_service_type(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private mlt_service_type(String swigName, mlt_service_type swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static mlt_service_type[] swigValues = { invalid_type, unknown_type, producer_type, tractor_type, playlist_type, multitrack_type, filter_type, transition_type, consumer_type, field_type };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

