/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.mltframework;

public interface mltConstants {
  public final static int PATH_MAX = mltJNI.PATH_MAX_get();
  public final static String MLT_POSITION_FMT = mltJNI.MLT_POSITION_FMT_get();
  public final static int LIBMLT_VERSION_MAJOR = mltJNI.LIBMLT_VERSION_MAJOR_get();
  public final static int LIBMLT_VERSION_MINOR = mltJNI.LIBMLT_VERSION_MINOR_get();
  public final static int LIBMLT_VERSION_REVISION = mltJNI.LIBMLT_VERSION_REVISION_get();
  public final static int LIBMLT_VERSION_INT = mltJNI.LIBMLT_VERSION_INT_get();
  public final static String LIBMLT_VERSION = mltJNI.LIBMLT_VERSION_get();
}
