/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.mltframework;

public class Service extends Properties {
  private long swigCPtr;

  protected Service(long cPtr, boolean cMemoryOwn) {
    super(mltJNI.Service_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Service obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mltJNI.delete_Service(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Service() {
    this(mltJNI.new_Service__SWIG_0(), true);
  }

  public Service(Service service) {
    this(mltJNI.new_Service__SWIG_1(Service.getCPtr(service), service), true);
  }

  public Service(SWIGTYPE_p_mlt_service_s service) {
    this(mltJNI.new_Service__SWIG_2(SWIGTYPE_p_mlt_service_s.getCPtr(service)), true);
  }

  public SWIGTYPE_p_mlt_service_s get_service() {
    long cPtr = mltJNI.Service_get_service(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_mlt_service_s(cPtr, false);
  }

  public void lock() {
    mltJNI.Service_lock(swigCPtr, this);
  }

  public void unlock() {
    mltJNI.Service_unlock(swigCPtr, this);
  }

  public SWIGTYPE_p_mlt_properties_s get_properties() {
    long cPtr = mltJNI.Service_get_properties(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_mlt_properties_s(cPtr, false);
  }

  public int connect_producer(Service producer, int index) {
    return mltJNI.Service_connect_producer__SWIG_0(swigCPtr, this, Service.getCPtr(producer), producer, index);
  }

  public int connect_producer(Service producer) {
    return mltJNI.Service_connect_producer__SWIG_1(swigCPtr, this, Service.getCPtr(producer), producer);
  }

  public Service consumer() {
    long cPtr = mltJNI.Service_consumer(swigCPtr, this);
    return (cPtr == 0) ? null : new Service(cPtr, true);
  }

  public Service producer() {
    long cPtr = mltJNI.Service_producer(swigCPtr, this);
    return (cPtr == 0) ? null : new Service(cPtr, true);
  }

  public Profile profile() {
    long cPtr = mltJNI.Service_profile(swigCPtr, this);
    return (cPtr == 0) ? null : new Profile(cPtr, false);
  }

  public SWIGTYPE_p_mlt_profile_s get_profile() {
    long cPtr = mltJNI.Service_get_profile(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_mlt_profile_s(cPtr, false);
  }

  public Frame get_frame(int index) {
    long cPtr = mltJNI.Service_get_frame__SWIG_0(swigCPtr, this, index);
    return (cPtr == 0) ? null : new Frame(cPtr, true);
  }

  public Frame get_frame() {
    long cPtr = mltJNI.Service_get_frame__SWIG_1(swigCPtr, this);
    return (cPtr == 0) ? null : new Frame(cPtr, false);
  }

  public mlt_service_type type() {
    return mlt_service_type.swigToEnum(mltJNI.Service_type(swigCPtr, this));
  }

  public int attach(Filter filter) {
    return mltJNI.Service_attach(swigCPtr, this, Filter.getCPtr(filter), filter);
  }

  public int detach(Filter filter) {
    return mltJNI.Service_detach(swigCPtr, this, Filter.getCPtr(filter), filter);
  }

  public int filter_count() {
    return mltJNI.Service_filter_count(swigCPtr, this);
  }

  public int move_filter(int from, int to) {
    return mltJNI.Service_move_filter(swigCPtr, this, from, to);
  }

  public Filter filter(int index) {
    long cPtr = mltJNI.Service_filter(swigCPtr, this, index);
    return (cPtr == 0) ? null : new Filter(cPtr, true);
  }

  public void set_profile(Profile profile) {
    mltJNI.Service_set_profile(swigCPtr, this, Profile.getCPtr(profile), profile);
  }

}
